ポケット・ミク

* これなに
  ふぁぼられた時、通常のふぁぼ通知の効果音のように、PCに接続されたポケット・ミクが「ふぁぼっ」と喋ってくれるプラグインです。

* インストール方法
  以下のコマンドでインストールできます。

#+BEGIN_SRC sh
  $ mkdir -p ~/.mikutter/plugin/; git clone https://github.com/toshia/mikutter_pocket_miku.git ~/.mikutter/plugin/pocket_miku/
#+END_SRC

  次に、bundlerを使っていない人は以下のコマンドを。

#+BEGIN_SRC sh
  $ gem install pocket_miku
#+END_SRC

  bundlerを使ってmikutterをセットアップした人は、mikutterのディレクトリでbundってください。

#+BEGIN_SRC sh
  $ bundle
#+END_SRC

* 使いかた
  デフォルトでは何もしません。
  設定の『ポケット・ミク』のmidiデバイスの項目に、ポケット・ミクの場所を設定してください。
  USBケーブルでPCとポケット・ミクを接続して、以下のコマンドを実行するとそれっぽいやつが出てくると思います。俺は /dev/midi2 でした。

#+BEGIN_SRC sh
  $ ls /dev/midi*
#+END_SRC

  最後に、ふぁぼ通知にチェックを入れます。このプラグインはいわゆるサウンドプラグインではないため、標準の通知サウンドを設定しているとそれも同時に鳴ってしまいます。ポケット・ミクだけでいいなら、設定の『通知』から、ふぁぼられた時の音を切ってください。

* 注意事項
  - 時間の同期のとり方がアレなので「ふぁーぼ」とか「ふぁぼー」とかになることがあります。
  - ふぁぼ爆耐性は計測していません。同時に通知音を発音できないためキューイングして順番に発音しますが、1ふぁぼにつき0.24秒程度かかります。これはキュー最高消化速度の0.1より長く、大量にキューイングされた通知音がなかなか鳴り止まない問題が考えられますし、製造元に問い合わせなかったところ、何ふぁぼまで耐えられるかは計測していないようです。使ってどうなってもしりませんが、壊れるとしたら俺のが最初だと思います。

* 今後
  - ふぁぼ以外の通知にも対応していきたい。
  - 通知音を変更できるようにしたい。ポケット・ミクのカーボンキーボードから入力できるようにしたい。
  - ポケット・ミクをふぁぼ通知デバイスにしたくない人生だった

* カスタマイズ
なんか魔改造したらぜひ
